// Copyright 2011 The Go Authors.  All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
	"text/template"
	"unicode"
	"unicode/utf8"
)

// A Command is an implementation of a command.
type Command struct {
	// Run runs the command.
	// The args are the arguments after the command name.
	Run func(cmd *Command, args []string)

	// UsageLine is the one-line usage message.
	// The first word in the line is taken to be the command name.
	UsageLine string

	// Short is the short description shown in the 'go help' output.
	Short string

	// Long is the long message shown in the 'go help <this-command>' output.
	Long string

	// Flag is a set of flags specific to this command.
	Flag flag.FlagSet

	// CustomFlags indicates that the command will do its own
	// flag parsing.
	CustomFlags bool
}

// Name returns the command's name: the first word in the usage line.
func (c *Command) Name() string {
	name := c.UsageLine
	i := strings.Index(name, " ")
	if i >= 0 {
		name = name[:i]
	}
	return name
}

func (c *Command) Usage() {
	fmt.Fprintf(os.Stderr, "usage: %s\n\n", c.UsageLine)
	fmt.Fprintf(os.Stderr, "%s\n", strings.TrimSpace(c.Long))
	os.Exit(2)
}

// Runnable reports whether the command can be run; otherwise
// it is a documentation pseudo-command such as importpath.
func (c *Command) Runnable() bool {
	return c.Run != nil
}

// Commands represents a set of commands.
type Commands []*Command

func (c Commands) Parse(args []string) error {
	if args[0] == "help" {
		return c.help(args[1:])
	}

	for _, cmd := range c {
		if cmd.Name() == args[0] && cmd.Run != nil {
			cmd.Flag.Usage = func() { cmd.Usage() }
			if cmd.CustomFlags {
				args = args[1:]
			} else {
				cmd.Flag.Parse(args[1:])
				args = cmd.Flag.Args()
			}
			cmd.Run(cmd, args)
			return nil
		}
	}
	return fmt.Errorf("Unknown subcommand %q.  Run `%s help` for usage.\n",
		args[0], os.Args[0])
}

// help implements the 'help' command.
func (c Commands) help(args []string) error {
	if len(args) == 0 { // Succeeded at 'go help'.
		c.printUsage(os.Stdout)
		return nil
	}
	if len(args) != 1 { // Failed at 'go help'.
		return fmt.Errorf("Usage: %s help command\n\nToo many arguments given.\n", os.Args[0])
	}

	arg := args[0]

	// 'go help documentation' generates doc.go.
	if arg == "documentation" {
		buf := new(bytes.Buffer)
		c.printUsage(buf)
		usage := &Command{Long: buf.String()}
		tmpl(os.Stdout, documentationTemplate, append([]*Command{usage}, c...))
		return nil
	}

	for _, cmd := range c {
		if cmd.Name() == arg { // Succeeded at 'go help cmd'.
			tmpl(os.Stdout, helpTemplate, cmd)
			return nil
		}
	}
	// Failed at 'go help cmd'
	return fmt.Errorf("Unknown help topic %q.  Run `%s help` for usage.\n", arg, os.Args[0])
}

func (c Commands) printUsage(w io.Writer) {
	tmpl(w, usageTemplate, c)
}

func (c Commands) Usage() {
	c.printUsage(os.Stderr)
	os.Exit(2)
}

// == Templates
//

var usageTemplate = `Go is a tool for managing Go source code.

Usage:

        {{program}} command [arguments]

The commands are:
{{range .}}{{if .Runnable}}
    {{.Name | printf "%-11s"}} {{.Short}}{{end}}{{end}}

Use "{{program}} help [command]" for more information about a command.
{{if hasExtraTopic .}}
Additional help topics:
{{range .}}{{if not .Runnable}}
    {{.Name | printf "%-11s"}} {{.Short}}{{end}}{{end}}

Use "{{program}} help [topic]" for more information about that topic.
{{end}}
`

var helpTemplate = `{{if .Runnable}}Usage: {{program}} {{.UsageLine}}

{{end}}{{.Long | trim}}
`

var documentationTemplate = `// Copyright 2011 The Go Authors.  All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// DO NOT EDIT THIS FILE. GENERATED BY mkdoc.sh.
// Edit the documentation in other files and rerun mkdoc.sh to generate this one.

/*
{{range .}}{{if .Short}}{{.Short | capitalize}}

{{end}}{{if .Runnable}}Usage:

        {{program}} {{.UsageLine}}

{{end}}{{.Long | trim}}


{{end}}*/
package main
`

// tmpl executes the given template text on data, writing the result to w.
func tmpl(w io.Writer, text string, data interface{}) {
	t := template.New("top")
	t.Funcs(template.FuncMap{
		"capitalize":    capitalize,
		"hasExtraTopic": hasExtraTopic,
		"program":       program,
		"trim":          strings.TrimSpace,
	})
	template.Must(t.Parse(text))
	if err := t.Execute(w, data); err != nil {
		panic(err)
	}
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	r, n := utf8.DecodeRuneInString(s)
	return string(unicode.ToTitle(r)) + s[n:]
}

func hasExtraTopic(cmds []*Command) bool {
	for _, v := range cmds {
		if !v.Runnable() {
			return true
		}
	}
	return false
}

func program() string {
	return os.Args[0]
}
