// Copyright 2011 The Go Authors.  All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Based in code from 'http://code.google.com/p/go/source/browse/src/cmd/go/main.go'

package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
	"text/template"
	"unicode"
	"unicode/utf8"
)

// A Command is an implementation of a command.
type Command struct {
	// Run runs the command.
	// The args are the arguments after the command name.
	Run func(cmd *Command, args []string)

	// UsageLine is the one-line usage message.
	// The first word in the line is taken to be the command name.
	UsageLine string

	// Short is the short description shown in the "<program> help" output.
	Short string

	// Long is the long message shown in the "<program> help <this-command>" output.
	Long string

	// Flag is a set of flags specific to this command.
	Flag flag.FlagSet

	// CustomFlags indicates that the command will do its own
	// flag parsing.
	CustomFlags bool
}

// Name returns the command's name: the first word in the usage line.
func (c *Command) Name() string {
	name := c.UsageLine
	i := strings.Index(name, " ")
	if i >= 0 {
		name = name[:i]
	}
	return name
}

func (c *Command) Usage() {
	fmt.Fprintf(os.Stderr, "Usage: %s %s\n\n", os.Args[0], c.UsageLine)
	os.Exit(2)
}

// Runnable reports whether the command can be run; otherwise
// it is a documentation pseudo-command such as importpath.
func (c *Command) Runnable() bool {
	return c.Run != nil
}

// Commands represents a set of commands.
type Commands struct {
	Description string // The program's description shown in the "<program> help" output.
	Commands    []*Command
}

func NewCommands(description string, cmds ...*Command) Commands {
	return Commands{description, cmds}
}

func (c Commands) Parse(args []string) error {
	if args[0] == "help" {
		return c.help(args[1:])
	}

	for _, cmd := range c.Commands {
		if cmd.Name() == args[0] && cmd.Run != nil {
			cmd.Flag.Usage = func() { cmd.Usage() }
			if cmd.CustomFlags {
				args = args[1:]
			} else {
				cmd.Flag.Parse(args[1:])
				args = cmd.Flag.Args()
			}
			cmd.Run(cmd, args)
			return nil
		}
	}
	return fmt.Errorf("Unknown subcommand %q.  Run `%s help` for usage.\n",
		args[0], os.Args[0])
}

// help implements the "help" command.
func (c Commands) help(args []string) error {
	if len(args) == 0 { // Succeeded at "<program> help".
		c.printUsage(os.Stdout)
		return nil
	}
	if len(args) != 1 { // Failed at "<program> help".
		return fmt.Errorf("Usage: %s help command\n\nToo many arguments given.\n", os.Args[0])
	}

	arg := args[0]

	// "<program> help documentation" generates full documentation of all commands.
	if arg == "documentation" {
		buf := new(bytes.Buffer)
		c.printUsage(buf)
		usage := &Command{Long: buf.String()}
		tmpl(os.Stdout, documentationTemplate, append([]*Command{usage}, c.Commands...))
		return nil
	}

	for _, cmd := range c.Commands {
		if cmd.Name() == arg { // Succeeded at "<program> help <cmd>".
			tmpl(os.Stdout, helpTemplate, cmd)
			return nil
		}
	}
	// Failed at "<program> help <cmd>"
	return fmt.Errorf("Unknown help topic %q.  Run `%s help` for usage.\n", arg, os.Args[0])
}

func (c Commands) printUsage(w io.Writer) {
	tmpl(w, usageTemplate, c)
}

func (c Commands) Usage() {
	c.printUsage(os.Stderr)
	os.Exit(2)
}

// == Templates
//

var usageTemplate = `{{.Description}}

Usage:

        {{program}} command [arguments]

The commands are:
{{range .Commands}}{{if .Runnable}}
    {{.Name | printf "%-11s"}} {{.Short}}{{end}}{{end}}

Use "{{program}} help [command]" for more information about a command.
{{if hasExtraTopic .Commands}}
Additional help topics:
{{range .Commands}}{{if not .Runnable}}
    {{.Name | printf "%-11s"}} {{.Short}}{{end}}{{end}}

Use "{{program}} help [topic]" for more information about that topic.
{{end}}
`

var helpTemplate = `{{if .Runnable}}Usage: {{program}} {{.UsageLine}}

{{end}}{{.Long | trim}}
{{if hasFlags .Flag}}
The flags are:
{{printDefaults .Flag}}{{end}}
`

var documentationTemplate = `// DO NOT EDIT THIS FILE. GENERATED BY "{{cmdLine}}".
// Edit the documentation in other files and re-run it to generate this one.

/*
{{range .}}{{if .Short}}{{.Short | capitalize}}

{{end}}{{if .Runnable}}Usage:

        {{program}} {{.UsageLine}}

{{end}}{{.Long | trim}}


{{end}}*/
package main
`

// tmpl executes the given template text on data, writing the result to w.
func tmpl(w io.Writer, text string, data interface{}) {
	t := template.New("top")
	t.Funcs(template.FuncMap{
		"capitalize":    capitalize,
		"hasExtraTopic": hasExtraTopic,
		"hasFlags":      hasFlags,
		"trim":          strings.TrimSpace,

		"cmdLine": func() string { return strings.Join(os.Args, " ") },
		"program": func() string { return os.Args[0] },
		"printDefaults": func(f flag.FlagSet) string {
			f.SetOutput(w)
			f.PrintDefaults()
			return ""
		},
	})
	template.Must(t.Parse(text))
	if err := t.Execute(w, data); err != nil {
		panic(err)
	}
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	r, n := utf8.DecodeRuneInString(s)
	return string(unicode.ToTitle(r)) + s[n:]
}

func hasExtraTopic(cmds []*Command) bool {
	for _, v := range cmds {
		if !v.Runnable() {
			return true
		}
	}
	return false
}

func hasFlags(f flag.FlagSet) bool {
	nFlags := 0

	f.VisitAll(func(*flag.Flag) {
		nFlags++
	})
	if nFlags != 0 {
		return true
	}
	return false
}

// == Values (from http://code.google.com/p/go/source/browse/src/pkg/flag/flag.go)
//

// -- string Value
type StringValue string

func newStringValue(val string, p *string) *StringValue {
	*p = val
	return (*StringValue)(p)
}

func (s *StringValue) Set(val string) error {
	*s = StringValue(val)
	return nil
}

func (s *StringValue) String() string { return fmt.Sprintf("%s", *s) }
