// Copyright 2013 Jonas mg
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package main

import (
	"fmt"
	"strconv"
	"strings"
)

const TEMPLATE_GO = `// {{.Command}}
// MACHINE GENERATED BY easycert (github.com/kless/easycert)
// From {{.System}} ({{.Arch}}) with "{{.Version}}", on {{.Date}}

package {{.Package}}

import (
	"crypto/tls"
	"log"
)

var TLSConfig *tls.Config

// Load certificate
func init() {
	CERT_PEM_BLOCK := {{.Cert}}

	KEY_PEM_BLOCK := {{.Key}}

	cert, err := tls.X509KeyPair(CERT_PEM_BLOCK, KEY_PEM_BLOCK)
	if err != nil {
		log.Fatal("load keys: ", err)
	}

	TLSConfig = &tls.Config{
		Certificates: []tls.Certificate{cert},
		// Can add other configuration fields
	}
}
`

// GoBlock represents the definition of a "[]byte" in Go.
type GoBlock []byte

func (b GoBlock) String() string {
	s := make([]string, len(b))

	for i, v := range b {
		if i != 0 && i%17 == 0 {
			s[i-1] = s[i-1][:len(s[i-1])-1] // remove anterior space
			s[i] = "\n\t\t"
		}
		s[i] += fmt.Sprintf("%s, ", strconv.Itoa(int(v)))
	}

	i := len(s) - 1
	s[i] = s[i][:len(s[i])-1] // remove last space

	return fmt.Sprintf("[]byte{\n\t\t%s\n\t}", strings.Join(s, ""))
}
